
export const pricingPlans = [
  {
    title: "Basic",
    description: "For individual investors getting started",
    price: "$0",
    period: "/month",
    features: [
      { text: "Connect up to 2 exchanges" },
      { text: "Basic performance tracking" },
      { text: "Portfolio allocation view" },
      { text: "Daily updates" },
    ],
    buttonText: "Get Started",
    buttonVariant: "outline" as const,
  },
  {
    title: "Pro",
    description: "For active investors with multiple accounts",
    price: "$5.99",
    period: "/month",
    features: [
      { text: "Connect up to 10 exchanges" },
      { text: "Advanced performance metrics" },
      { text: "Portfolio allocation & analysis" },
      { text: "Real-time updates" },
      { text: "Mobile app access" },
    ],
    isPopular: true,
    buttonText: "Get Started",
    buttonVariant: "default" as const,
  },
  {
    title: "Enterprise",
    description: "For professional investors and teams",
    price: "$17.99",
    period: "/month",
    features: [
      { text: "Unlimited exchange connections" },
      { text: "Professional analytics with custom AI agent" },
      { text: "Advanced risk assessment" },
      { text: "Real-time updates" },
      { text: "Team collaboration features" },
      { text: "Priority support" },
      { text: "Customizable dashboards" },
    ],
    buttonText: "Contact Sales",
    buttonVariant: "outline" as const,
  },
];
