export enum Routes {
  HOME = '/',
  LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  DASHBOARD = '/dashboard',
  PROFILE = '/profile',
  FEATURES = '/features',
  INTEGRATIONS = '/integrations',
  PRICING = '/pricing',
  SUPPORT = '/support',
  TERMS = '/terms',
  PRIVACY = '/privacy',
  CONTACT = '/contact',
  SETTINGS = '/settings',
  DASHBOARD_PORTFOLIO = '/dashboard/portfolio',
  ALL_TRANSACTIONS = '/dashboard/transactions',
  PLATFORMS = '/dashboard/platforms',
  ACCOUNT = '/account',
}