export enum Routes {
  HOME = "/",
  LOGIN = "/auth/login",
  REGISTER = "/auth/register",
  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  FEATURES = "/features",
  INTEGRATIONS = "/integrations",
  PRICING = "/pricing",
  SUPPORT = "/support",
  TERMS = "/terms",
  PRIVACY = "/privacy",
  CONTACT = "/contact",
  SETTINGS = "/settings",
  ADD_YOUR_OWN_ASSET = "/add-your-own-asset",
  CONNECT_TRADING212 = "/connect/trading212",
  CONNECT_ETORO = "/connect/etoro",
  CONNECT_BINANCE = "/connect/binance",
  CONNECT_CRYPTO_COM = "/connect/crypto-com",
  CONNECT_COINBASE = "/connect/coinbase",
  DASHBOARD_PORTFOLIO = "/dashboard/portfolio",
  ALL_TRANSACTIONS = "/dashboard/transactions",
  PLATFORMS = "/dashboard/platforms",
  ACCOUNT = "/account",
  DOCS = "/docs",
  TODOS = "/todo",
  COMING_SOON = "/coming-soon",
}
